import pygame.mixer

pygame.mixer.init(48000, -16, 1, 1024)

soundOne = pygame.mixer.sound("filepath")
soundTwo = pygame.mixer.sound("filepath")
soundThree = pygame.mixer.sound("filepath")
soundFour = pygame.mixer.sound("filepath")
soundFive = pygame.mixer.sound("filepath")
soundSix = pygame.mixer.sound("filepath")
soundSeven = pygame.mixer.sound("filepath")
soundEight = pygame.mixer.sound("filepath")
soundNine = pygame.mixer.sound("filepath")
soundTen = pygame.mixer.sound("filepath")
soundEleven = pygame.mixer.sound("filepath")
soundTwelve = pygame.mixer.sound("filepath")

soundChannelOne = pygame.mixer.Channel(1)
soundChannelTwo = pygame.mixer.Channel(2)
soundChannelThree = pygame.mixer.Channel(3)
soundChannelFour = pygame.mixer.Channel(4)
soundChannelFive = pygame.mixer.Channel(5)
soundChannelSix = pygame.mixer.Channel(6)
soundChannelSeven = pygame.mixer.Channel(7)
soundChannelEight = pygame.mixer.Channel(8)
soundChannelNine = pygame.mixer.Channel(9)
soundChannelTen = pygame.mixer.Channel(10)
soundChannelEleven = pygame.mixer.Channel(11)
soundChannelTwelve = pygame.mixer.Channel(12)
